### ISSUE TITLE
Issues when creating new record from UI 2

### ISSUE THREAD

**Issue by zakiuu** [acsone/scobidoo#11]
When using the fix  made in a4983d5 I'm having a stack trace:
```
Traceback (most recent call last):
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/modules/loading.py", line 414, in load_modules
    model._register_hook(cr)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo9-addon-statechart/setup/statechart/odoo_addons/statechart/models/statechart_mixin.py", line 308, in _register_hook
    _sc_patch(self, cr, SUPERUSER_ID)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo9-addon-statechart/setup/statechart/odoo_addons/statechart/models/statechart_mixin.py", line 279, in _sc_patch
    dummy_interpreter = dummy.sc_interpreter
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/fields.py", line 868, in __get__
    self.determine_draft_value(record)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/fields.py", line 1000, in determine_draft_value
    self.compute_value(record)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/fields.py", line 946, in compute_value
    self._compute_value(records)
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo/openerp/fields.py", line 923, in _compute_value
    getattr(records, self.compute)()
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo9-addon-statechart/setup/statechart/odoo_addons/statechart/models/statechart_mixin.py", line 80, in _compute_sc_interpreter
    interpreter.execute_once()
  File "/Users/zakaria/Ascone/odoo-silog/src/odoo9-addon-statechart/setup/statechart/odoo_addons/statechart/models/interpreter.py", line 42, in execute_once
    return super(Interpreter, self).execute_once()
  File "/Users/zakaria/Ascone/odoo-silog/src/sismic/sismic/interpreter/interpreter.py", line 234, in execute_once
    executed_steps.extend(self._stabilize())
  File "/Users/zakaria/Ascone/odoo-silog/src/sismic/sismic/interpreter/interpreter.py", line 545, in _stabilize
    steps.append(self._apply_step(step))
  File "/Users/zakaria/Ascone/odoo-silog/src/sismic/sismic/interpreter/interpreter.py", line 514, in _apply_step
    sent_events.extend(self._evaluator.execute_onentry(state))
  File "/Users/zakaria/Ascone/odoo-silog/src/sismic/sismic/code/python.py", line 423, in execute_onentry
    return self._execute_code(getattr(state, 'on_entry', None), context=self._contexts[state.name])
  File "/Users/zakaria/Ascone/odoo-silog/src/sismic/sismic/code/python.py", line 361, in _execute_code
    raise_from(CodeEvaluationError('The above exception occurred while executing:\n{}'.format(code)), e)
  File "/Users/zakaria/.virtualenvs/odoo-silog2/lib/python2.7/site-packages/future/utils/__init__.py", line 454, in raise_from
    raise e
AttributeError: 'function' object has no attribute 'origin'
```
- After debugging the code the error is coming from the `on entry` actions of my initial state:
```YML
states:
      - name: draft                                                             # Brouillon
        on entry: |
          o.suspend_security().write({'silog_state': 'draft'})
          o.button_draft.origin(o.suspend_security())
```

**Comment by sbidoul** [comment]
```AttributeError: 'function' object has no attribute 'origin'```

**Comment by sbidoul** [comment]
I think it's because the o_button_draft is not patched when computing the default values.

We must look if we can patch the methods before creating the sc_allowed fields.

**Comment by sbidoul** [comment]
@zakiuu should be ok now. I added a test for your use case.

**Comment by zakiuu** [comment]
@sbidoul thanks for the help!
