### ISSUE TITLE
[12.0][issue]after install 'statechart_demo_purchase',  when click button 'Confirm Order', will be error

### ISSUE THREAD

**Issue by joycehuan** [acsone/scobidoo#20]
Install demo module 'statechart_demo_purchase'.

```
2019-01-18 11:23:26,229 39401 ERROR odoo12-sc odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/interpreter.py", line 40, in execute_once
    return super(Interpreter, self).execute_once()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/interpreter/default.py", line 305, in execute_once
    executed_steps.append(self._apply_step(step))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/interpreter/default.py", line 668, in _apply_step
    sent_events.extend(self._evaluator.execute_action(step.transition, step.event))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/code/evaluator.py", line 97, in execute_action
    return self._execute_code(transition.action, additional_context={'event': event})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/code/python.py", line 176, in _execute_code
    raise CodeEvaluationError('"{}" occurred while executing "{}"'.format(e, code)) from e
sismic.exceptions.CodeEvaluationError: "Reentrancy error for Event('button_approve') on purchase.order(6,). Please use sc_queue() instead of a direct method call. " occurred while executing "# TODO this is not a very nice way to invoke the origin method
o.button_confirm.origin(o, *event.args, **event.kwargs)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/Users/joyce/project/elico/agrigarden/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/joyce/project/elico/agrigarden/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/Users/joyce/project/elico/agrigarden/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/statechart_mixin.py", line 202, in partial
    return self._sc_exec_event(event)
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/statechart_mixin.py", line 131, in _sc_exec_event
    rec._sc_execute(interpreter, event)
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/statechart_mixin.py", line 104, in _sc_execute
    steps = interpreter.execute()
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/interpreter.py", line 30, in execute
    return super(Interpreter, self).execute(max_steps)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/interpreter/default.py", line 259, in execute
    macro_step = self.execute_once()
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/interpreter.py", line 42, in execute_once
    raise _root_cause(e).with_traceback(sys.exc_info()[2])
  File "/Users/joyce/project/elico/agrigarden/add_addons/scobidoo/statechart/models/interpreter.py", line 40, in execute_once
    return super(Interpreter, self).execute_once()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/interpreter/default.py", line 305, in execute_once
    executed_steps.append(self._apply_step(step))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/interpreter/default.py", line 668, in _apply_step
    sent_events.extend(self._evaluator.execute_action(step.transition, step.event))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/code/evaluator.py", line 97, in execute_action
    return self._execute_code(transition.action, additional_context={'event': event})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sismic/code/python.py", line 176, in _execute_code
    raise CodeEvaluationError('"{}" occurred while executing "{}"'.format(e, code)) from e
RuntimeError: Reentrancy error for Event('button_approve') on purchase.order(6,). Please use sc_queue() instead of a direct method call. 
```
Base V12 standard ODOO
If  click button 'Confirm Order', will be invoke function ```button_confirm```.
![image](https://user-images.githubusercontent.com/12812722/51384668-f818f280-1b57-11e9-8e19-47c30eb950ea.png)

then in this function, standard ODOO,  ```order.button_approve()``` will produce the error.

![image](https://user-images.githubusercontent.com/12812722/51384850-8beabe80-1b58-11e9-96dc-915292284777.png)

So , if define the event name on ```statechart.yml```, could not invoke the same name function on backend code ?

**Comment by sbidoul** [comment]
Statechart calls are indeed not reentrant. In short, this is because while executing a transition action the next state is not yet set. So we need to use a queuing mechanism. You can use [sc_queue](https://github.com/acsone/scobidoo/blob/15920d6c4802f52fca2686544c8318576406a920/statechart/models/statechart_mixin.py#L63) if you need to do reentrant calls. To call the original method from within a statechart action, use `self.button_approve.origin(self)` to call the original, unpatched method, as you have noticed.

Note that, despite the name, statechart_demo_purchase is not really a demo module, it's more a test module that exercises all kind of weird situations.

The best demo to start with is the one in my Odoo Experience slides.

**Comment by joycehuan** [comment]
>Statechart calls are indeed not reentrant. In short, this is because while executing a transition action the next state is not yet set. So we need to use a queuing mechanism. You can use sc_queue if you need to do reentrant calls. To call the original method from within a statechart action, use self.button_approve.origin(self) to call the original, unpatched method, as you have noticed.

>Note that, despite the name, statechart_demo_purchase is not really a demo module, it's more a test >module that exercises all kind of weird situations.

>The best demo to start with is the one in my Odoo Experience slides.

OK, Thanks
